[package]
name = "photo-gallery-backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "photo-gallery-backend"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["cors"] }

aws-sdk-s3 = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-iam = { version = "1", features = ["behavior-version-latest"] }
aws-config = { version = "1", features = ["behavior-version-latest"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
